services:
  - type: web
    name: whitelegacy
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn milkapp_project.wsgi:application --workers=1 --threads=1
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: your_razorpay_key_id
      - key: RAZORPAY_KEY_SECRET
        value: your_razorpay_key_secret
    staticPublishPath: staticfiles
