# Generated by Django 5.2.3 on 2025-06-22 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_healthlog_submitted_by_milkdelivery_submitted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='milkdelivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='milkinglog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='healthlog',
            name='buffalo_number',
            field=models.CharField(default='B001', max_length=10),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='milkinglog',
            name='buffalo_number',
            field=models.CharField(default='B001', max_length=10),
        ),
        migrations.AddField(
            model_name='milkinglog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milkdelivery',
            name='customer_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='milkdelivery',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milkinglog',
            name='milk_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkinglog',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
