# Generated by Django 5.2.3 on 2025-06-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_contactmessage_subscriptionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionrequest',
            old_name='litres_required',
            new_name='litre_needed',
        ),
    ]
