# Generated by Django 5.2.3 on 2025-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_rename_litres_required_subscriptionrequest_litre_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=150),
            preserve_default=False,
        ),
    ]
